name: Build and Deploy

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Use Node.js 12.x
          uses: actions/setup-node@v1
          with:
              node-version: 12.x
        - name: npm install, build, and test
          run: |
              npm ci
              npm run build
          env:
              CI: true
        - name: deploy to Heroku
          env:
              HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
              HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          if: github.ref == 'refs/heads/master' && job.status == 'success'
          run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
